### ISSUE TITLE
Failed to activate the dynamicengine-tools package

### ISSUE THREAD

**Issue by inceptusp** [github-vipera/dynamicengine-tools#3]
[Enter steps to reproduce:]

1. Installing the plugin or
2. Creating a new project

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: elementary OS
**Thrown From**: [dynamicengine-tools](https://github.com/github-vipera/dynamicengine-tools) package 2.5.9

### Stack Trace

Failed to activate the dynamicengine-tools package

```
At Cannot find module 'JQuery'

Error: Cannot find module 'JQuery'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/dynamicengine-tools/lib/runconfig/RunSettingsUIHandler.js:11:15)
    at /packages/dynamicengine-tools/lib/runconfig/RunSettingsUIHandler.js:8:42)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/dynamicengine-tools/lib/dynamicengine-tools.js:6:48)
    at /packages/dynamicengine-tools/lib/dynamicengine-tools.js:358:2)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:937:35)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:244:22)
    at /usr/share/atom/resources/app/src/package.js:1022:31
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:360:24)
```

### Commands

```
     -3:32.6.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:02.5.0 dynamicengine-tools:create-project (button.btn.btn-primary)
```

### Non-Core Packages

```
dynamicengine-tools 2.5.9 
```

**Comment by marcobonati** [comment]
Hi Pedro
thanks for your interest and feedback.
I want to warn you that this tool is currently deprecated and you can use this instead:
[de-workbench](https://github.com/github-vipera/de-workbench)

This project contains all the features of dynamicengine-tools and additional features as well as support for Cordova 8 and the latest Android and iOS platforms.

regards

**Comment by inceptusp** [comment]
Oh, cool... Thx

**Comment by inceptusp** [comment]
I'm having an issue with the package you said me to install, I opened an Issue here: https://github.com/github-vipera/de-workbench/issues/2
